language: python
python: 3.4
os: linux
compiler: gcc
addons:
    apt:
        packages:
            - libboost-test-dev
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n test python=3.6
    - source $HOME/miniconda/bin/activate test
    - conda install --yes gsl numpy scipy h5py
    - git submodule update --init --recursive
    - python3 --version
install:
    - pip install runtests
    - python3 setup.py install
script:
    - python3 do_the_tests.py
    - make test

deploy:
    - provider: pypi
      distributions: sdist
      user: "simeonbird"
      password:
         secure: "i5VN3uQMm3vDmEfpjqhYM0PgIr2R3F3aa9O2LDhiW2TzQEjOYlZ6G7xnCL0QojJFJbyQCKNVSs6W6TGNA8RBnUvZe9sFyhFKCHz7dvW4nSuV50zjjeunR3HmSFkFxJi4N3MJkj+woTMNkQTYlDNRu6+SbpHaFFtuawhIjk6IUWx7pYsPwO9QeV+7uALcgxkiifLhwKegjsifHrSjuHhQWkjP1hrRwxrYIcaoTOtF6irMMXCFrI5cfa2lk5IHueT1RqsmsrrX2gM1pohRZyn5T6Snu31E8T3eyexNi7kJWaBC2Y9d5xVnMAC+KoZhPfC+PPW5NaIj3UKdMKB0tG8H9P2/kPdaRa4yzqjd+1FnGfvSr5A3OQv34VFgJXeMX+9ss1MMw4Qjkj6IJG3GMs4yxaAVI7OJjr5KDLW0NiDAHvRr8QIN/BM9WtLqpMbna2/WSto0+QzUjBQFFnYcg/X8KVgVu+XdfVgoj0QPH/Fx2VqQrv/lF96oVmqJNw+1oKwDakuj6ZxYrfwWdFuI20vELLsuPiwVKYMDJuLapEDkPBSSAu2EJI+1HduNlDa28cD2TlT+jLjz+bGwNhRzzLxcDsR7Qo6zD6oYhQX6uP9OMFi/S3jC4NF74tm0URVigi0UxPYXUd5VQOGbr7Er7t8hSRZdLDXnu6rxsDvx2sa2cds="
      on:
          tags: true
          condition: ${TRAVIS_JOB_NUMBER##*.} == 1
